<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('currencies')->insert([

            [ 'name' => 'Afghan Afghani' ],
            [ 'name' => 'Albanian Lek' ],
            [ 'name' => 'Algerian Dinar' ],
            [ 'name' => 'Angolan Kwanza' ],
            [ 'name' => 'Argentine Peso' ],
            [ 'name' => 'Armenian Dram' ],
            [ 'name' => 'Aruban Florin' ],
            [ 'name' => 'Australian Dollar' ],
            [ 'name' => 'Azerbaijani Manat' ],
            [ 'name' => 'Bahamian Dollar' ],
            [ 'name' => 'Bahraini Dinar' ],
            [ 'name' => 'Bangladeshi Taka' ],
            [ 'name' => 'Barbadian Dollar' ],
            [ 'name' => 'Belarusian Ruble' ],
            [ 'name' => 'Belize Dollar' ],
            [ 'name' => 'Bermudian Dollar' ],
            [ 'name' => 'Bhutanese Ngultrum' ],
            [ 'name' => 'Bolivian Boliviano' ],
            [ 'name' => 'Bosnia and Herzegovina Convertible Mark' ],
            [ 'name' => 'Botswana Pula' ],
            [ 'name' => 'Brazilian Real' ],
            [ 'name' => 'British Pound' ],
            [ 'name' => 'Brunei Dollar' ],
            [ 'name' => 'Bulgarian Lev' ],
            [ 'name' => 'Burundian Franc' ],
            [ 'name' => 'Cambodian Riel' ],
            [ 'name' => 'Canadian Dollar' ],
            [ 'name' => 'Cape Verdean Escudo' ],
            [ 'name' => 'Cayman Islands Dollar' ],
            [ 'name' => 'Central African CFA Franc' ],
            [ 'name' => 'Chilean Peso' ],
            [ 'name' => 'Chinese Yuan' ],
            [ 'name' => 'Colombian Peso' ],
            [ 'name' => 'Comorian Franc' ],
            [ 'name' => 'Congolese Franc' ],
            [ 'name' => 'Costa Rican Colón' ],
            [ 'name' => 'Croatian Kuna' ],
            [ 'name' => 'Cuban Peso' ],
            [ 'name' => 'Czech Koruna' ],
            [ 'name' => 'Danish Krone' ],
            [ 'name' => 'Djiboutian Franc' ],
            [ 'name' => 'Dominican Peso' ],
            [ 'name' => 'East Caribbean Dollar' ],
            [ 'name' => 'Egyptian Pound' ],
            [ 'name' => 'Eritrean Nakfa' ],
            [ 'name' => 'Estonian Kroon' ],
            [ 'name' => 'Ethiopian Birr' ],
            [ 'name' => 'Euro' ],
            [ 'name' => 'Fijian Dollar' ],
            [ 'name' => 'Gambian Dalasi' ],
            [ 'name' => 'Georgian Lari' ],
            [ 'name' => 'Ghanaian Cedi' ],
            [ 'name' => 'Gibraltar Pound' ],
            [ 'name' => 'Guatemalan Quetzal' ],
            [ 'name' => 'Guinean Franc' ],
            [ 'name' => 'Guyanese Dollar' ],
            [ 'name' => 'Haitian Gourde' ],
            [ 'name' => 'Honduran Lempira' ],
            [ 'name' => 'Hong Kong Dollar' ],
            [ 'name' => 'Hungarian Forint' ],
            [ 'name' => 'Icelandic Króna' ],
            [ 'name' => 'Indian Rupee' ],
            [ 'name' => 'Indonesian Rupiah' ],
            [ 'name' => 'Iranian Rial' ],
            [ 'name' => 'Iraqi Dinar' ],
            [ 'name' => 'Israeli New Shekel' ],
            [ 'name' => 'Jamaican Dollar' ],
            [ 'name' => 'Japanese Yen' ],
            [ 'name' => 'Jordanian Dinar' ],
            [ 'name' => 'Kazakhstani Tenge' ],
            [ 'name' => 'Kenyan Shilling' ],
            [ 'name' => 'Kuwaiti Dinar' ],
            [ 'name' => 'Kyrgyzstani Som' ],
            [ 'name' => 'Lao Kip' ],
            [ 'name' => 'Latvian Lats' ],
            [ 'name' => 'Lebanese Pound' ],
            [ 'name' => 'Lesotho Loti' ],
            [ 'name' => 'Liberian Dollar' ],
            [ 'name' => 'Libyan Dinar' ],
            [ 'name' => 'Lithuanian Litas' ],
            [ 'name' => 'Macanese Pataca' ],
            [ 'name' => 'Macedonian Denar' ],
            [ 'name' => 'Malagasy Ariary' ],
            [ 'name' => 'Malawian Kwacha' ],
            [ 'name' => 'Malaysian Ringgit' ],
            [ 'name' => 'Maldivian Rufiyaa' ],
            [ 'name' => 'Mauritanian Ouguiya' ],
            [ 'name' => 'Mauritian Rupee' ],
            [ 'name' => 'Mexican Peso' ],
            [ 'name' => 'Moldovan Leu' ],
            [ 'name' => 'Mongolian Tögrög' ],
            [ 'name' => 'Moroccan Dirham' ],
            [ 'name' => 'Mozambican Metical' ],
            [ 'name' => 'Myanmar Kyat' ],
            [ 'name' => 'Namibian Dollar' ],
            [ 'name' => 'Nepalese Rupee' ],
            [ 'name' => 'Netherlands Antillean Guilder' ],
            [ 'name' => 'New Taiwan Dollar' ],
            [ 'name' => 'New Zealand Dollar' ],
            [ 'name' => 'Nicaraguan Córdoba' ],
            [ 'name' => 'Nigerian Naira' ],
            [ 'name' => 'North Korean Won' ],
            [ 'name' => 'Norwegian Krone' ],
            [ 'name' => 'Omani Rial' ],
            [ 'name' => 'Pakistani Rupee' ],
            [ 'name' => 'Panamanian Balboa' ],
            [ 'name' => 'Papua New Guinean Kina' ],
            [ 'name' => 'Paraguayan Guaraní' ],
            [ 'name' => 'Peruvian Sol' ],
            [ 'name' => 'Philippine Peso' ],
            [ 'name' => 'Polish Złoty' ],
            [ 'name' => 'Qatari Riyal' ],
            [ 'name' => 'Romanian Leu' ],
            [ 'name' => 'Russian Ruble' ],
            [ 'name' => 'Rwandan Franc' ],
            [ 'name' => 'Saint Helena Pound' ],
            [ 'name' => 'São Tomé and Príncipe Dobra' ],
            [ 'name' => 'Saudi Riyal' ],
            [ 'name' => 'Serbian Dinar' ],
            [ 'name' => 'Seychellois Rupee' ],
            [ 'name' => 'Sierra Leonean Leone' ],
            [ 'name' => 'Singapore Dollar' ],
            [ 'name' => 'Slovak Koruna' ],
            [ 'name' => 'Solomon Islands Dollar' ],
            [ 'name' => 'Somali Shilling' ],
            [ 'name' => 'South African Rand' ],
            [ 'name' => 'South Korean Won' ],
            [ 'name' => 'Sri Lankan Rupee' ],
            [ 'name' => 'Sudanese Pound' ],
            [ 'name' => 'Surinamese Dollar' ],
            [ 'name' => 'Swazi Lilangeni' ],
            [ 'name' => 'Swedish Krona' ],
            [ 'name' => 'Swiss Franc' ],
            [ 'name' => 'Syrian Pound' ],
            [ 'name' => 'Tajikistani Somoni' ],
            [ 'name' => 'Tanzanian Shilling' ],
            [ 'name' => 'Thai Baht' ],
            [ 'name' => 'Tongan Paanga' ],
            [ 'name' => 'Trinidad and Tobago Dollar' ],
            [ 'name' => 'Tunisian Dinar' ],
            [ 'name' => 'Turkish Lira' ],
            [ 'name' => 'Turkmenistani Manat' ],
            [ 'name' => 'Ugandan Shilling' ],
            [ 'name' => 'Ukrainian Hryvnia' ],
            [ 'name' => 'United Arab Emirates Dirham' ],
            [ 'name' => 'United States Dollar' ],
            [ 'name' => 'Uruguayan Peso' ],
            [ 'name' => 'Uzbekistani Som' ],
            [ 'name' => 'Vanuatu Vatu' ],
            [ 'name' => 'Venezuelan Bolívar' ],
            [ 'name' => 'Vietnamese Dong' ],
            [ 'name' => 'West African CFA Franc' ],
            [ 'name' => 'Yemeni Rial' ],
            [ 'name' => 'Zambian Kwacha' ],
            [ 'name' => 'Zimbabwean Dollar' ]

        ]);
    }
}
